name: cmip-ohu-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - pip
  - pip:
      - sphinx-pythia-theme
  - matplotlib
  - numpy
  - xarray
  - intake
  - intake-esm
  - gcsfs
  - nc-time-axis
  - cmip6_preprocessing
  - xarrayutils
